#!/bin/env bash

# enable local backups
ENABLE_LOCAL_BACKUPS=true

# local backup vars
BUCKET_SUBDIR=${BUCKET_SUBDIR:-"default"}
LOCAL_BACKUP_PATH=${LOCAL_BACKUP_PATH:-"/backup"}

# generate whole backup path
BACKUP_PATH="$LOCAL_BACKUP_PATH/$BUCKET_SUBDIR/$DB_TYPE"
