#!/bin/env bash

# local backup vars
SUBDIR=${SUBDIR:-"default"}
LOCAL_BACKUP_PATH=${LOCAL_BACKUP_PATH:-"/backup"}

# set backup path
BACKUP_PATH="$LOCAL_BACKUP_PATH/$SUBDIR/$DB_TYPE"

# create backup folder if it does not exist
mkdir -p "$BACKUP_PATH" || fail "couldn't create backup folder. check your permissions."
