#!/bin/env bash

# version info / gets replaced in the CI
VERSION="!!TAG!!"

DEBUG=${DEBUG:-false}

# source script options
SOURCE_LOCATION=${SOURCE_LOCATION:-"/usr/share/backup-job"}
BACKUP_ENVIRONMENT=${BACKUP_ENVIRONMENT:-"kubernetes-wsp"}

# skip backup option
YES_I_DONT_NEED_BACKUPS_AND_DOCUMENTED_THIS_SOMEWHERE=${YES_I_DONT_NEED_BACKUPS_AND_DOCUMENTED_THIS_SOMEWHERE:-"NO"}

# Database
DB_TYPE=${DB_TYPE:-"postgres"} # postgres / mariadb / mysql / mongodb / pvc
DB_USER=${DB_USER:-"postgres"}
DB_PASSWORD=${DB_PASSWORD:-"password"}
DB_PORT=${DB_PORT:-"5432"}
DB_HOST=${DB_HOST:-"localhost"}

# PVC
PVC_DATA_LOCATION=${PVC_DATA_LOCATION:-"/data"}

# Time for the timestamp
DATE_TIME=`date +%Y-%m-%d--%H-%M`

# Dump tmp destination 
DUMP_NAME="${DATE_TIME}-backup.sql.gz"
DUMP_DEST="/tmp/${DUMP_NAME}"

# get binaries
PGDUMP=`which pg_dumpall`
MYSQLDUMP=`which mysqldump`
MCLI=`which mcli`
MONGO=`which mongodump`
TAR=`which tar`

# local path params
ENABLE_LOCAL_BACKUPS_ONLY=${ENABLE_LOCAL_BACKUPS_ONLY:-false}
LOCAL_BACKUP_PATH=${LOCAL_BACKUP_PATH:-"/backup"}

# retention params