#!/bin/env bash

# stage specific settings
STAGE_NAME=${CLUSTER_STAGE_NAME:-"develop"}

# S3 params
BUILD_URL="${CLUSTER_STAGE_S3_URL_PROTOCOL:-"http"}://${CLUSTER_STAGE_S3_URL}"
S3_URL=${BUILD_URL:-"http://s3.local"}
S3_KEY_ID=${CLUSTER_STAGE_S3_ACCESS_KEY:-"backupkey"}
S3_KEY_SECRET=${CLUSTER_STAGE_S3_SECRET_KEY:-"supersecret"}
S3_BUCKET_NAME=${CLUSTER_STAGE_S3_BUCKET_NAME_BACKUP:-"backup"}
# folder in which to put the dump on S3 backend
S3_BUCKET_SUBDIR=${BUCKET_SUBDIR:-"default"}

